# Generated by Django 4.1.7 on 2023-05-13 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipa', models.CharField(max_length=200)),
                ('sigla_equipa', models.CharField(max_length=5)),
                ('data_criacao', models.DateTimeField(verbose_name='data de criacao')),
                ('emblema_clube', models.CharField(default='default_emblem.png', max_length=50)),
            ],
            options={
                'permissions': (('write_inscrever_numa_equipa', 'o utilizador pode inscrever e desinscrever-se numa equipa'), ('write_delete_Equipa', 'o utilizador pode criar equipas, apagar equipas e remover atletas da equipa')),
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=200)),
                ('pub_data_evento', models.DateTimeField(verbose_name='data de publicacao')),
                ('data_evento', models.DateTimeField(verbose_name='data do evento')),
                ('local_evento', models.CharField(max_length=300)),
                ('descricao_evento', models.CharField(max_length=500)),
                ('num_equipas', models.IntegerField(default=1)),
                ('equipas', models.ManyToManyField(to='gestaoequipas.equipa')),
            ],
            options={
                'permissions': (('write_delete_alocacao_eventos', 'o utilizador pode criar eventos, apagar eventos e inscrever em eventos'),),
            },
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.CharField(default='default.png', max_length=50)),
                ('equipa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoequipas.equipa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_texto', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipas.evento')),
            ],
            options={
                'permissions': (('read_write_confirmar_presenca', 'o utilizador pode confirmar presença num evento'),),
            },
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_perfil', models.CharField(default='default.png', max_length=50)),
                ('equipa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atletas', to='gestaoequipas.equipa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
