# Generated by Django 4.1.7 on 2023-05-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoequipas', '0002_respostapossivel_remove_response_response_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='atleta',
        ),
    ]
