# Generated by Django 4.1.7 on 2023-05-13 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoequipas', '0003_remove_response_atleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='atleta',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestaoequipas.atleta'),
            preserve_default=False,
        ),
    ]
