# Generated by Django 4.1.7 on 2023-05-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoequipas', '0004_response_atleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoequipas.respostapossivel'),
        ),
    ]
