# Generated by Django 4.1.7 on 2023-05-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoequipas', '0006_alter_evento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'permissions': (('write_delete_alocacao_eventos', 'o utilizador pode criar eventos, apagar eventos e inscrever em eventos'),)},
        ),
    ]
