# Generated by Django 4.1.7 on 2023-05-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoequipas', '0007_alter_evento_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Response',
        ),
    ]
