# Generated by Django 4.1.7 on 2023-05-13 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoequipas', '0008_delete_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipas.atleta')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipas.evento')),
                ('response', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaoequipas.respostapossivel')),
            ],
            options={
                'permissions': (('read_write_confirmar_presenca', 'o utilizador pode confirmar presença num evento'),),
            },
        ),
    ]
