# Generated by Django 4.1.7 on 2023-05-13 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoequipas', '0010_rename_response_resposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='atleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipas.atleta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestaoequipas.evento'),
        ),
    ]
